main: test.o file_read.o calculations.o student_division.o file_generation.o file_output.o
	g++ -o main -O2 main.cpp test.o file_read.o calculations.o student_division.o file_generation.o file_output.o
fun:
	g++ -c test.cpp file_read.cpp calculations.cpp student_division.cpp file_generation.cpp file_output.cpp